Re-implement sys-clk-Editor using a state machine
SunTheCourier/sys-clk-Editor pull request #18
Opened 2019-12-24 11:07 UTC by cathery

sun i'm so sorry

- Switch to a state machine similar to SPR manager
- Add multiple program states besides Enabled and Disabled (similar to SPR manager)
- Change "Delete config" to "Clear config", and actually clear the config

i haven't tested it completely, i don't remember how your gameSelected and configSelected variables are supposed to behave, please test to make sure everything works the same

2019-12-24 19:40 UTC, SunTheCourier commented
with a state machine ameSelected and configSelected should no longer be necessary afaik as they were used to return to the correct selection on the last page

2019-12-24 19:41 UTC, gabehxd requested changes

2019-12-24 19:41 UTC, SunTheCourier commented on source/States/ConfigMenu.h
> +    virtual void Enter() override {}
virtuals are redundant

2019-12-25 05:15 UTC, cathery commented on source/States/ClockMenus.h
> +    virtual void Enter() override {}
```suggestion
    void Enter() override {}
```

2019-12-25 05:15 UTC, cathery commented on source/States/ClockMenus.h
> +    virtual void Update(StateMachine &, u64) override;
```suggestion
    void Update(StateMachine &, u64) override;
```

2019-12-25 05:16 UTC, cathery commented on source/States/ClockMenus.h
> +    virtual void Exit() override {}
```suggestion
    void Exit() override {}
```

2019-12-25 05:16 UTC, cathery commented on source/States/ClockMenus.h
> +    virtual std::string Name() override { return "mem"; }
```suggestion
    std::string Name() override { return "mem"; }
```

2019-12-25 05:16 UTC, cathery commented on source/States/ClockMenus.h
> +    virtual ~MEMMenu() override {}
```suggestion
    ~MEMMenu() override {}
```

2019-12-25 05:16 UTC, cathery commented on source/States/ClockMenus.h
> +    virtual void Enter() override {}
```suggestion
    void Enter() override {}
```

2019-12-25 05:16 UTC, cathery commented on source/States/ClockMenus.h
> +    virtual void Update(StateMachine &, u64) override;
```suggestion
    void Update(StateMachine &, u64) override;
```

2019-12-25 05:16 UTC, cathery commented on source/States/ClockMenus.h
> +    virtual void Exit() override {}
```suggestion
    void Exit() override {}
```

2019-12-25 05:17 UTC, cathery commented on source/States/ClockMenus.h
> +    virtual std::string Name() override { return "gpu"; }
```suggestion
    std::string Name() override { return "gpu"; }
```

2019-12-25 05:17 UTC, cathery commented on source/States/ClockMenus.h
> +    virtual ~GPUMenu() override {}
```suggestion
    ~GPUMenu() override {}
```

2019-12-25 05:17 UTC, cathery commented on source/States/ClockMenus.h
> +    virtual void Enter() override {}
```suggestion
    void Enter() override {}
```

2019-12-25 05:17 UTC, cathery commented on source/States/ClockMenus.h
> +    virtual void Update(StateMachine &, u64) override;
```suggestion
    void Update(StateMachine &, u64) override;
```

2019-12-25 05:17 UTC, cathery commented on source/States/ClockMenus.h
> +    virtual void Exit() override {}
```suggestion
    void Exit() override {}
```

2019-12-25 05:17 UTC, cathery commented on source/States/ClockMenus.h
> +    virtual std::string Name() override { return "cpu"; }
```suggestion
    std::string Name() override { return "cpu"; }
```

2019-12-25 05:18 UTC, cathery commented on source/States/ClockMenus.h
> +    virtual ~CPUMenu() override {}
```suggestion
    ~CPUMenu() override {}
```

2019-12-25 05:18 UTC, cathery commented on source/States/ConfigMenu.h
> +    virtual void Enter() override {}
```suggestion
    void Enter() override {}
```

2019-12-25 05:18 UTC, cathery commented on source/States/ConfigMenu.h
> +    virtual void Update(StateMachine &, u64) override;
```suggestion
    void Update(StateMachine &, u64) override;
```

2019-12-25 05:18 UTC, cathery commented on source/States/ConfigMenu.h
> +    virtual void Exit() override {}
```suggestion
    void Exit() override {}
```

2019-12-25 05:18 UTC, cathery commented on source/States/ConfigMenu.h
> +    virtual std::string Name() override { return "config"; }
```suggestion
    std::string Name() override { return "config"; }
```

2019-12-25 05:18 UTC, cathery commented on source/States/ConfigMenu.h
> +    virtual ~ConfigMenu() override {}
```suggestion
    ~ConfigMenu() override {}
```

2019-12-25 05:19 UTC, cathery commented on source/States/ErrorMenu.h
> +    virtual void Enter() override {}
```suggestion
    void Enter() override {}
```

2019-12-25 05:19 UTC, cathery commented on source/States/ErrorMenu.h
> +    virtual void Update(StateMachine &, u64) override;
```suggestion
    void Update(StateMachine &, u64) override;
```

2019-12-25 05:19 UTC, cathery commented on source/States/ErrorMenu.h
> +    virtual void Exit() override {}
```suggestion
    void Exit() override {}
```

2019-12-25 05:19 UTC, cathery commented on source/States/ErrorMenu.h
> +    virtual std::string Name() override { return "error"; }
```suggestion
    std::string Name() override { return "error"; }
```

2019-12-25 05:19 UTC, cathery commented on source/States/ErrorMenu.h
> +    virtual ~ErrorMenu() override {}
```suggestion
    ~ErrorMenu() override {}
```

2019-12-25 05:19 UTC, cathery commented on source/States/MainMenu.h
> +    virtual void Enter() override;
```suggestion
    void Enter() override;
```

2019-12-25 05:19 UTC, cathery commented on source/States/MainMenu.h
> +    virtual void Update(StateMachine &, u64) override;
```suggestion
    void Update(StateMachine &, u64) override;
```

2019-12-25 05:20 UTC, cathery commented on source/States/MainMenu.h
> +    virtual void Exit() override {}
```suggestion
    void Exit() override {}
```

2019-12-25 05:20 UTC, cathery commented on source/States/MainMenu.h
> +    virtual std::string Name() override { return "main"; }
```suggestion
    std::string Name() override { return "main"; }
```

2019-12-25 05:20 UTC, cathery commented on source/States/MainMenu.h
> +    virtual ~MainMenu() override {}
```suggestion
    ~MainMenu() override {}
```

2019-12-25 05:20 UTC, cathery commented on source/States/TitleMenu.h
> +    virtual void Enter() override {}
```suggestion
    void Enter() override {}
```

2019-12-25 05:20 UTC, cathery commented on source/States/TitleMenu.h
> +    virtual void Update(StateMachine &, u64) override;
```suggestion
    void Update(StateMachine &, u64) override;
```

2019-12-25 05:21 UTC, cathery commented on source/States/TitleMenu.h
> +    virtual void Exit() override {}
```suggestion
    void Exit() override {}
```

2019-12-25 05:21 UTC, cathery commented on source/States/TitleMenu.h
> +    virtual std::string Name() override { return "title"; }
```suggestion
    std::string Name() override { return "title"; }
```

2019-12-25 05:21 UTC, cathery commented on source/States/TitleMenu.h
> +    virtual ~TitleMenu() override {}
```suggestion
    ~TitleMenu() override {}
```

2019-12-25 05:22 UTC, gabehxd approved these changes

2019-12-26 09:00 UTC, gabehxd requested changes

2019-12-26 09:00 UTC, gabehxd commented on source/States/ClockMenus.cpp
> +    if (kDown & KEY_UP)
nitpick but single line these?

2019-12-26 09:00 UTC, gabehxd commented on source/States/ClockMenus.h
> +    void Enter() override {}
empty implementations are not necessary for overrides as they are virtual

2019-12-26 09:00 UTC, gabehxd commented on source/States/ErrorMenu.h
> +
lots of extra spaces

2019-12-26 09:00 UTC, SunTheCourier commented
just nitpicking really

2019-12-27 04:08 UTC, gabehxd approved these changes

2019-12-27 04:36 UTC, SunTheCourier commented
all seems good in testing 👌

2019-12-27 04:36 UTC, merged